public enum Symbol {
    IDENT, Number,
    TIMES, PLUS, MINUS, DIV,
    INT, VOID, MAIN, PRINT, READ,
    EOL, ERROR, EOF,
    OPEN_PAR, CLOSE_PAR, OPEN_BRACE, CLOSE_BRACE,
    SEMICOLON, COMA, ASSIGN
}
